# There is a built-in micro proxy that will host the webui and REST API all on
# one port (this is called the "Single HTTP Frontend") and means you just need
# one open port in the container/firewalls/etc.
#
# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337

# Choose from INFO (default), WARN and DEBUG
logLevel: "INFO"

# Checking for updates https://docs.olivetin.app/update-checks.html
checkForUpdates: false

showFooter: false

themeName: dark-mode
pageTitle: re:3D
sectionNavigationStyle: topbar

#ACTIONS
actions:

    # Uses Ping to check the connection to the printer
  - title: Check Printer Connection
    shell: ping -c 3 192.168.4.2
    icon: <iconify-icon icon="material-symbols:wifi" width="48" height="48"></iconify-icon>
    popupOnStart: execution-dialog-stdout-only

  # Grabs the klippy log from the printer
  - title: Grab Logs
    shell: /home/pi/saved_scripts/save_log.sh
    icon: <iconify-icon icon="icon-park-outline:log" width="48" height="48"></iconify-icon>
    popupOnStart: default

  # Displays the mainsail interface
  - title: Interface Pop-up
    icon: <iconify-icon icon="uil:rss-interface" width="48" height="48"></iconify-icon>
    shell: su - pi -c "chromium-browser --no-sandbox --kiosk --zoom=100 file:///home/pi/interface.html"
    popupOnStart: default

  # Uses the klipper script to generate a certain type of graph based on user choice (Dynamic Graph and Type)
  - title: Generate Load Graph
    icon: <iconify-icon icon="lets-icons:img-load-box-fill" width="48" height="48"></iconify-icon>
    timeout: 20
    shell: |
      /home/pi/klipper/scripts/graphstats.py /home/pi/saved_logs/{{ Log }} {{ Type }} -o /home/pi/graph.png
      /home/pi/klipper/scripts/graphstats.py /home/pi/saved_logs/{{ Log }} {{ Type }} -o /home/pi/saved_graphs/graph$(date +"%T").png
    popupOnStart: default
    trigger: Display Last Loadgraph
    arguments:
      - name: Log
        entity: log
        choices:
          - value: "{{ log.Name }}"
            title: "{{ log.Name }}"
      - name: Type
        choices:
          - title: mcu bandwidth & load utilization
            value: ""
          - title: mcu frequency
            value: "-f"
          - title: system load
            value: "-s"
          - title: heater temperature
            value: "-t HEATER"

  # Finds the graph.png that was made from the previous command and uses chromium to display it with an iframe
  - title: Display Last Loadgraph
    shell: su - pi -c "chromium-browser --no-sandbox --kiosk --zoom=100 file:///home/pi/graph_display.html"
    icon: <iconify-icon icon="mdi:graph-line" width="48" height="48"></iconify-icon>
    popupOnStart: default

  # Displays what errors were found in a file and some possible solutions to different problems.
  - title: Display Errors in Log
    shell: python /home/pi/saved_scripts/parse_log.py /home/pi/saved_logs/{{ Log }}
    icon: <iconify-icon icon="bxs:error" width="48" height="48"></iconify-icon>
    timeout: 20
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: Log
        entity: log
        choices:
          - value: "{{ log.Name }}"
            title: "{{ log.Name }}"

# Uses the klippy log to display the last known temperatures by looking at the end of the file for the last occurance of it
  - title: Display Extruder Temps
    shell: python /home/pi/saved_scripts/parse_extruders.py /home/pi/saved_logs/{{ Log }}
    icon: <iconify-icon icon="fluent:temperature-24-filled" width="48" height="48"></iconify-icon>
    timeout: 20
    popupOnStart: execution-dialog-stdout-only
    arguments:
      - name: Log
        entity: log
        choices:
          - value: "{{ log.Name }}"
            title: "{{ log.Name }}"
  
  # Uses moonraker to send an API command of the inputted GCode CMD to the printer via the IP Address
  - title: Manual GCode
    shell: python /home/pi/saved_scripts/manual_gcode.py {{ GCode }}
    icon: <iconify-icon icon="mdi:console-line" width="48" height="48"></iconify-icon>
    arguments:
      - name: GCode
        type: ascii_sentence

  # Using the dd command it flashes the inserted SD Card (sda)
  - title: Flash IMG to SD Card
    shell: "dd if=home/pi/re3D-KlipperV0-5-0.img of=/dev/sda bs=4M status=progress && sync"
    icon: <iconify-icon icon="mdi:sd-card" width="48" height="48"></iconify-icon>
    popupOnStart: execution-dialog-stdout-only
    timeout: 1000
  
  # Exports all the Logs and Graphs that are stored in saved_logs and saved_graphs to the sda device.
  - title: Export Logs & Graphs
    shell: "/home/pi/saved_scripts/copy_to_usb.sh"
    icon: <iconify-icon icon="mdi:file-export" width="48" height="48"></iconify-icon>
    popupOnStart: execution-dialog-stdout-only
    timeout: 15

  # ACTIONS FOR HEATER CONTROL TAB:

  # Sets the temperature of the extruder/heater bed
  - title: Set {{ temps.name }} Temp
    shell: python /home/pi/saved_scripts/set_temp.py {{ temps.name }} {{ Temperature }}
    entity: temps
    icon: <iconify-icon icon="carbon:temperature-inversion" width="48" height="48"></iconify-icon>
    arguments:
      - name: Temperature
        type: int
  
  # Cools the temperature of the extruder/heater bed to 0 celsius
  - title: Cooldown {{ temps.name }}
    shell: python /home/pi/saved_scripts/set_temp.py {{ temps.name }} 0
    entity: temps
    icon: <iconify-icon icon="mdi:snowflake" width="48" height="48"></iconify-icon>
  
  # Grabs the most recent data from the printer via moonraker
  - title: Refresh Data
    shell: python /home/pi/saved_scripts/printer_data.py
    icon: <iconify-icon icon="solar:refresh-bold" width="48" height="48"></iconify-icon>
    popupOnStart: execution-dialog-stdout-only

  # HELP TAB ACTIONS
  # Displays a page that shows short descriptions of all the actions
  - title: Help
    shell: su - pi -c "chromium-browser --no-sandbox --kiosk --zoom=100 file:///home/pi/help.html"
    icon: <iconify-icon icon="material-symbols:help" width="48" height="48"></iconify-icon>
    popupOnStart: default
  
  # Reconnects the Pi to the keyboard if a disconnect happens
  - title: Bluetooth Connect
    shell: /home/pi/saved_scripts/btconnect.sh
    icon: <iconify-icon icon="material-symbols:bluetooth" width="48" height="48"></iconify-icon>
    timeout: 15
    popupOnStart: default
  
  # Uses a sequence of keys to get the terminal open for more advanced technical debugging via the command line
  - title: Terminal Popup
    shell: /home/pi/saved_scripts/terminal_pop.sh
    icon: <iconify-icon icon="material-symbols:terminal" width="48" height="48"></iconify-icon>
    popupOnStart: execution-dialog-stdout-only
  
  # Deletes the .json file that holds all the names of the files, and then removes them from the device via rm
  - title: Delete All Logs & Graphs
    shell: | 
      > /etc/OliveTin/entities/logs.json
      rm -r -f home/pi/saved_logs/*
      rm -r -f home/pi/saved_graphs/*
    icon: <iconify-icon icon="material-symbols:delete" width="48" height="48"></iconify-icon>
    popupOnStart: default
  

  # Lastly, you can hide actions from the web UI, this is useful for creating
  # background helpers that execute only on startup or a cron, for updating
  # entity files.

  # - title: Update container entity file
  #   shell: 'docker ps -a --format json > /etc/OliveTin/entities/containers.json'
  #   hidden: true
  #   execOnStartup: true
  #   execOnCron: '*/1 * * * *'

# An entity is something that exists - a "thing", like a VM, or a Container
# is an entity. OliveTin allows you to then dynamically generate actions based
# around these entities.
#
# This is really useful if you want to generate wake on lan or poweroff actions
# for `server` entities, for example.
#
# A very popular use case that entities were designed for was for `container`
# entities - in a similar way you could generate `start`, `stop`, and `restart`
# container actions.
#
# Entities are just loaded fome files on disk, OliveTin will also watch these
# files for updates while OliveTin is running, and update entities.
#
# Entities can have properties defined in those files, and those can be used
# in your configuration as variables. For example; `container.status`,
# or `vm.hostname`.
#
# Docs: http://docs.olivetin.app/entities.html
entities:
  
  # Holds the names of all the logs held on the Pi
  - file: /etc/OliveTin/entities/logs.json
    name: log
  
  # Holds the system data that was refreshed from the printer 
  - file: /etc/OliveTin/entities/system_data.json
    name: system
  
  # Holds the printer temperatures that were refreshed from the printer
  - file: /etc/OliveTin/entities/printer_temps.json
    name: temps

# Dashboards are a way of taking actions from the default "actions" view, and
# organizing them into groups - either into folders, or fieldsets.
#
# The only way to properly use entities, are to use them with a `fieldset` on
# a dashboard.
dashboards:
  
  # HEATER CONTROL DASHBOARD
  # ACTIONS: Refresh Data, Set [NAME] Temp, Cooldown [NAME]
  - title: Heater Control
    contents:
      - title: "Printer Data"
        entity: system
        type: fieldset
        contents:
          - type: display
            title: |
             <strong>{{ system.printer.hostname }}</strong> MAC: {{ system.system.mac_address }}
          - title: Refresh Data
      
      - title: "{{ temps.name }}"
        entity: temps
        type: fieldset
        contents:
          - type: display
            title: |
                Current: <strong>{{ temps.current }}</strong>
                Target: <strong>{{ temps.target }}</strong>
          
          - title: Set {{ temps.name }} Temp
          - title: Cooldown {{ temps.name }}

  # HELP DASHBOARD
  # ACTIONS: Bluetooth Connect, Help, Terminal Popup, Delete All Logs & Graphs
  - title: Help
    contents:
      - title: "Help"
        type: fieldset
        contents:
          - title: Bluetooth Connect
          - title: Help
          - title: Terminal Popup
          - title: Delete All Logs & Graphs
